- Gemfile
- Gemfile.lock
- app/jobs/process_job.rb
**Fixes bug where job fails here if no terms are returned**
Job on a CSV importing refname values instead of term strings was
failing here because `result.terms` was empty, causing `missing_terms`
to be `nil` instead of empty in the next line.
**Use collectionspace-mapper v2.1.4**
No longer warns about `%NULLVALUE%` being a malformed refname
> Fix ProcessJob bug for results with no terms

- app/controllers/connections_controller.rb
- app/controllers/users_controller.rb
- app/helpers/application_helper.rb
- app/models/connection.rb
- app/models/user.rb
- app/policies/batch_policy.rb
- app/policies/connection_policy.rb
- app/views/batches/_form.html.erb
- app/views/connections/_form.html.erb
- db/migrate/20200822160258_create_connections.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/connections_controller_test.rb
- test/fixtures/connections.yml
- test/fixtures/mappers.yml
- test/models/connection_test.rb
- test/models/mapper_test.rb
- test/system/users_manager_test.rb
Currently a user's connections are not tied to a particular group,
since that feature was introduced (recently-ish). This is confusing
so now the current group context is applied as the group for a
connection so a user can have different connections for each group
they are a part of.
> Scope connection to group more strictly

- app/controllers/step/processes_controller.rb
- app/models/step/process.rb
- app/views/step/processes/_step.html.erb
- config/locales/en.yml
- db/migrate/20210413184444_remove_check_records_from_step_processes.rb
- db/migrate/20210413184509_remove_check_terms_from_step_processes.rb
- db/schema.rb
- test/controllers/step/process_controller_test.rb
Removes Check records and Check terms checkboxes from Process step, as decided in dev meeting with Megan. Documentation for users starting a migration into a completely empty CSpace will say how to use the JSON batch config to turn this off in the relatively rare case that it is safe to use
> Removes Check records and Check terms checkboxes from Process step

- app/jobs/process_job.rb
- app/services/record_transfer_service.rb
`cspace-batch-import` should not have to know about the internals of
the mapper structure. `collectionspace-mapper` is already all up in
the mapper structure and should be able to tell the importer what it
needs to know cleanly through the DataHandler interface.
`RecordTransferService` still has a couple of mapper excavations to
get rid of, but they are not immediate problems, so they'll be on the
list for later improvements
> use handler.service_type instead of digging into config

- app/controllers/batches_controller.rb
- app/models/batch.rb
- app/views/batches/_form.html.erb
Closes #97 
Well, it doesn't really fix the problem in #97 which is an invalid/badly structured CSV file. 
This tool is not a magical CSV structure fixing tool, so it can't fix that. 
This fixes the issue where the app was falling over when form template flash shown when the CSV fails initial validation was sent a *string* of the `Csvlint::ErrorMessage` instead of the actual object. (The error message, etc. is over at #97)
It eliminates showing the first 5 errors and instead instructs the user to take their CSV over to https://csvlint.io/ and remediate their CSV.
The `Csvlint::ErrorMessage` had `@category=:structure` and `@type=:unknown_error`. The webapp actually gives usable info (but unfortunately, its "Download Standardised CSV" button did NOT magically fix the issue).
> Gh97 cannot create new batch

- Gemfile
- Gemfile.lock
This release fixes an annoying spurious warning about unknown option
list values, and adds a batch config option needed from migration work.
> use collectionspace-mapper v2.5.0

- app/services/record_transfer_service.rb
Follow example [here](https://ruby-doc.org/stdlib-2.7.4/libdoc/uri/rdoc/URI.html) instead of using `URI.encode`.
Closes #131 
See also: https://bugs.ruby-lang.org/issues/16469 (This is warning
about `URI.encode`, though the message is for `URI.escape`
> Fix URI.escape warning

- Gemfile
- Gemfile.lock
The new version adds an option necessary for clients to update existing records that may have leading/trailing spaces in the record ID field: 
https://github.com/collectionspace/collectionspace-mapper/releases/tag/v2.5.2
> bump collectionspace-mapper version

- app/models/mapper.rb
- app/services/step_manager_service.rb
- test/controllers/step/preprocesses_controller_test.rb
- test/job_helper.rb
As we're always specifying the content type we don't need AS to do
this for us, and it's actually a problem in some cases (like when
a csv report contains embedded html).
> Disable ActiveStorage content inspection

- Gemfile
- Gemfile.lock
- README.md
- app/models/batch.rb
- app/models/connection.rb
- config/application.rb
- test/models/connection_test.rb
Reverts collectionspace/collectionspace-csv-importer#156
Incompatibility between Zeitwerk in Mapper and Rails production mode (eager loading enabled). Can be found with:
```
./bin/rails zeitwerk:check
```
Or run development with `config.eager_load = true`
Some related~ish looking info (but haven't had time to read through it):
- https://makandracards.com/makandra/498915-heads-up-byebug-has-problems-with-zeitwerk
- https://github.com/deivid-rodriguez/byebug/issues/564
- https://github.com/ruby/debug/issues/408
> Revert "changes related to migration tooling"

- Gemfile
- Gemfile.lock
- README.md
- app/models/batch.rb
- app/models/connection.rb
- config/application.rb
- test/models/connection_test.rb
- eager load collectionspace-mapper to pass `zeitwerk:check` (as per [statement from zeitwerk maintainer](https://github.com/ruby/debug/issues/408#issuecomment-985989827))
- Initialize `CollectionSpace::Mapper::DataHandler` with a client-less RefCache
- Add `csid_cache` parameter to constructor for `CollectionSpace::Mapper::DataHandler` -- Since the only way to search for relations is by subject/object CSID, we need a way to efficiently look up CSIDs. Since I'm already setting up `collectionspace-mapper` to work with two separate `CollectionSpace::RefCache` instances for migration tooling stuff---one for refnames for terms, and one for CSIDs---it is much more straightforward to just make it always use two separate RefCaches for these two separate types of information. When …
> bump mapper version to fix zeitwerk problem

- app/models/group.rb
- app/views/groups/_form.html.erb
- app/views/groups/_users.html.erb
- test/fixtures/users.yml
- test/models/group_test.rb
When deleting a group if an associated user is affiliated with
another group then reassign the user to an available group. Only
delete the users that are exclusively associated with the group
being deleted.
This also adds an abbrev. assigned user table to a group page.
> Update Delete Group functionality, resolves #168

- Gemfile
- Gemfile.lock
Fixes an error that could cause a record with a bad date format to not process. 
I found this issue basically at the same time you were merging my last PR, so it was too late to be sneaked in there.
> use collectionspace-mapper v4.0.3 (date parsing bugfix)

- app/jobs/reaper_unused_job.rb
- app/models/manifest.rb
- config/sidekiq.yml
- test/models/manifest_test.rb
Enable identification of unused manifests (all mappers have 0
batches). Clear out unused manifests on a monthly basis.
> Manifest cleanup

- app/models/manifest.rb
- app/views/manifests/_row.html.erb
- app/views/manifests/index.html.erb
- config/locales/en.yml
- db/migrate/20220625065955_add_protected_column_to_manifest.rb
- db/schema.rb
- db/seeds.rb
- test/fixtures/manifests.yml
- test/models/manifest_test.rb
Used in determining whether a manifest is active / unused. When
enabled a manifest is not eligible for auto-deletion via bg job.
For this reason enabled is represented as "Protected" in the UI.
> Adds enabled property to Manifest

- Gemfile
- Gemfile.lock
- app/services/missing_term_service.rb
- removes reporting of missing term identifiers (as they do not have any) - I think/hope this is what was causing failures recently reported for OHC, WESTAF, and UCJEPS, although I was not able to reproduce the prod error exactly in local dev environment/testing
- use v4.0.4 of `collectionspace-mapper` which no longer outputs duplicate missing term errors when a client search does not find a term
> Missing term handling

- Gemfile
- Gemfile.lock
- app/jobs/process_job.rb
- bump collectionspace-mapper version to get failed-to-parse URN value in error message
- log full `handler.process` error backtrace
> Log full process error

- Gemfile
- Gemfile.lock
This release of collectionspace-mapper fixes a couple of known, lingering date processing issues.
The new processing warnings/errors[^1] users may see have already been added to [the Error/Warning reference in the User Manual](https://collectionspace.atlassian.net/wiki/spaces/COL/pages/2276589604/User+Manual+CSV+Importer+Error+and+Warning+Reference)
[^1]: Error messages shown in Importer UI and reports, not exception errors!
> bump collectionspace-mapper to v4.0.7

- Gemfile
- Gemfile.lock
This fixes a bug where year-only dates with less than four digits produce CSXML that does not validate in the ingest process.
> Use collectionspace-mapper 4.1.1

- app/controllers/batches_controller.rb
- app/views/batches/_form.html.erb
It looks like the error behavior has changed to **not** pop up in a temporary, small widget thingie. It now displays at the bottom of the form page, and seems to stay there until you move off the page. 
Because of this, it was way more straightforward to just show the validation errors in this same interface. 
Since a too-long CSV and an invalid CSV are two separate issues, I separated the flash that gets triggered for each. 
I moved the error message to the top of the result/redirected form, since it is the most important thing to know. (Before making any changes I created 3 invalid batches wondering why I was getting NO error messages at all, before realizing they were just at the bottom of the screen and I needed to scroll down to see them.)
I tested this locally, but could not figure …
> Display csvlint errors

- Gemfile
- Gemfile.lock
collectionspace-mapper 4.1.2 fixes a bug that could make the Processing step fail if an unparseable-to-structured-date 2-digit year date string was encountered.
> Use collectionspace-mapper 4.1.2

- Gemfile
- Gemfile.lock
Adds support for importing new Chronology authority record types
Minitest suite passed on my local dev environment and I was able to [load chronology event terms to core](https://core.collectionspace.org/cspace/core/list/chronology/event?size=20&p=1) and [chronology field collection terms to anthro](https://anthro.collectionspace.org/cspace/anthro/list/chronology/fieldcollection?size=20&p=1)
> Use collectionspace-client 0.15.1

- app/models/batch.rb
There have been cases where the mapper content has changed but caching on title means the incorrect mapper is being used until the cache expires. Caching on digest should be fine in all cases.
> Cache mapper on digest not title

- app/jobs/process_job.rb
- app/models/batch.rb
- app/services/record_transfer_service.rb
service_type is derived from the record mapper, which exists before and separate from the DataHandler.
> Remove dependency on collectionspace-mapper DataHandler to get service_type

- Gemfile
- Gemfile.lock
Details of fix in lyrasis/csvlint.rb#2
> DRYD-1252: Use fork of csvlint that fixes multiline roundtripping

- app/controllers/application_controller.rb
- app/controllers/batches_controller.rb
- app/models/batch.rb
- app/views/batches/_form.html.erb
- test/controllers/batches_controller_test.rb
- test/fixtures/files/crlf_eol_final_cr_eol.csv
- test/fixtures/files/csvlint_invalid.csv
Resolves #213 
Currently, you are allowed to proceed to the pre-processing step
with such a file, but the job fails when preprocessing hits a row that
causes a CSV::MalformedCSVError. Unfortunately, this often occurs at
the very end of the file.
This commit adds a separate csv_parse_validator_for(batch) method
that is only called if Csvlint reports the file is valid.
CSV-Parsing the whole file before creating the batch may seem like
overkill, but (a) I can't come up with a better way to catch all
possible issues; and (b) it seems better than using system
resources/user time to pre-process a whole batch that is only going to
fail at the end.
Thinking forward: If we are eventually moving to using the database to
store information about each row and its state/status, then this step
can be …
> DRYD 1490 Catch issues Csvlint validates, but Ruby CSV library can’t parse

- app/models/connection.rb
- test/models/connection_test.rb
This password must match a user's CollectionSpace login password, which does not have a 6-18 character length limitation.
> Remove password length constraint on Connection password

- Gemfile
- Gemfile.lock
- 6.0.3 Absorbs exception raised when multiple records found when checking record status by id, and reports as a processing row error instead
- 6.0.4 Replaces limited case-insensitive fallback search with use of ILIKE (with no % qualifiers) operator for full case-insensitivity
> Use collectionspace-mapper 6.0.4

- Gemfile
- Gemfile.lock
- app/controllers/batches_controller.rb
- app/views/batches/_form.html.erb
- test/controllers/batches_controller_test.rb
- test/fixtures/files/crlf_eol_final_cr_eol.csv
v1.4.0.6 = post-merge of PR#6 in lyrasis fork.
This update fixes the problem of the row count of CSVs with \r EOL always being set to 1, which causes CSV Importer to calculate ridiculously huge percent done values as it processes all the actual rows. 
The changes to csvlint mean none of my test CSVs now trigger the situation handled/tested by the removed code. The specific situation handled is now reported as invalid by csvlint, so we don't need to have specific handling for it in this application.
> Use csvlint v1.4.0.6

- app/models/step/preprocess.rb
Connection authentication check was added to all workflow steps in [PR 200](https://github.com/collectionspace/collectionspace-csv-importer/pull/200), but removed (kept in only the processing and transferring steps) as part of refactoring/cleanup in [PR 204](https://github.com/collectionspace/collectionspace-csv-importer/pull/204).
This PR adds this check back to the preprocessing step, on the principle of saving the user time and effort. They should find out about an unusable connection to CollectionSpace ASAP when starting on a batch. If that's not at batch creation time, then it should be in the preprocessing step.
Resolves #226
> Validate connection on Preprocess step

- Gemfile
- Gemfile.lock
- app/jobs/process_job.rb
1. Bumps collectionspace-mapper to a new bugfix version to fix ZD26342
2. Stop instructing people to email the Program team when there's an unexpected processing error.
> Bump mapper version and fix error message
